name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [check, build, clippy, test, fmt]
        include:
          - flags: ""
          - check: clippy
            flags: "-- -D clippy::all --no-deps"
          - check: fmt
            flags: "-- --check"
          - check: test
            flags: "-- --nocapture"
    name: ${{ matrix.check }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          profile: minimal
          toolchain: stable
      - name: Cargo ${{ matrix.check }}
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.check }}
          args: ${{ matrix.flags }}
  
